#!/bin/bash

if [ $# -ne 1 ]; then
    echo "error"
    exit
fi
fname=$1
filename=${fname%%.*}.cpp
if [[ -f ./$filename ]]; then
    echo "The specified file is already exists.\n"
    exit
fi
cp template.cpp $filename
code $filename
